---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/small-git }

platform: linux

inputs:
  - name: cf-networking-release-ci

outputs:
  - name: release-notes

run:
  path: cf-networking-release-ci/ci/cf-networking-ci/tasks/build-release-notes

params:
  OUTPUT_DIR: release-notes
